url: 'https://beyond-hd.me'
host: beyond-hd.me
siteName: BHD
imdb: '.movie-details a[href*="imdb.com/title"]:nth-child(1)'
insertDomSelector: '.movie-wrapper'
doubanContainerDom: '<div class="douban-dom bhd"></div>'