url: 'https://karagarga.in'
host: karagarga.in
siteName: KG
imdb: 'td a[href*="imdb.com/title"]:first'
insertDomSelector: '.outer h1~table:first'
doubanContainerDom: '<div class="douban-dom kg" style="width:770px;padding-top:20px;"></div>'