url: https://secret-cinema.pw
host: secret-cinema.pw
siteName: SC
imdb: '.torrent_row a[href*="imdb.com/title"]:first'
insertDomSelector: '.linkbox:first'
doubanContainerDom: '<div class="douban-dom sc"></div>'